$schema: ./config.schema.json
instruction:
  compilerOptions:
    strictNullChecks: true
    strict: true
    target: ES2018
    noEmit: true
    lib: [ESNext]
  schemaSettings:
    required: true
  input:
    - ./types.ts
  list:
    - symbol: Config
      output: config.schema.json
